apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geth-app
  template:
    metadata:
      labels:
        app: geth-app
    spec:
      containers:
      - name: geth-node
        image: mygeth
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        command: ["sleep", "infinity"]
